### ISSUE TITLE
[Feature Request] Use BTCPayserver

### ISSUE THREAD

**Issue by JPyke3** [alfg/guildbit#46]
Hey There!

Just stumbled upon the project today and was really blown away by how cool it is! Hats off to you!

I was thinking of throwing a few Satoshis your way but saw that you were only accepting on-chain bitcoin payments. Whilst easy to do there are a few issues.

## Issues

The first is privacy, It's very easy to trace any payments coming in or out of your address, the donations you earn will be forever linked to you.

The second is the on-chain transaction fees, whilst BTC is great for a lot of things, the speed and the transaction fees (especially whilst the mempool is as rammed as it is right now) are not the highlights. 

## Enhancement

Perhaps something you could look into to fix this issue would be something like this: https://btcpayserver.org/

This way you would be able to change address for every donation you receive, and furthermore, accept payments on the Lightning Network, a fee-less and instant payment system powered by the Bitcoin blockchain.

If you end up going through and setting it up, might chuck 5 or so EUR your way ;)

**Comment by alfg** [comment]
Hey @JPyke3, 

Thank you for the kind words! I'm glad you like the project. :)

I don't currently have any plans to support BTCPay at the moment. However, I am in the process is reworking some of the payment upgrade code and I will check into btcpayserver.org as an option.

Thanks for the input!
